/whill_simulator:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  # # Velocity Controller
  # right_wheel_velocity_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: rightWheel
  #   pid: {p: 100.0,i: 0.01, d: 10.0}

  # left_wheel_velocity_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: leftWheel
  #   pid: {p: 100.0,i: 0.01, d: 10.0}

  diff_drive_controller:
    type        : "diff_drive_controller/DiffDriveController"
    left_wheel  : 'leftWheel'
    right_wheel : 'rightWheel'

    publish_rate: 20.0
    cmd_vel_timeout: 1.0
    wheel_separation : 0.49
    wheel_radius : 0.1325
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    # tf
    #enable_odom_tf: true
    base_frame_id: base_floor
    odom_frame_id: odom

    # limits
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           :  0.55 # m/s
        min_velocity           : -0.55 # m/s
        has_acceleration_limits: true
        max_acceleration       :  1.0 # m/s^2
        min_acceleration       : -1.0 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           :  1.5 # rad/s
        min_velocity           : -1.5 # rad/s
        has_acceleration_limits: true
        max_acceleration       :  1.0  # rad/s^2
        min_acceleration       : -1.0 # rad/s^2